on:
  schedule:
    - cron: '0 0 * * *'
env:
  DOCKER_USERNAME: percygrunwald
  IMAGE_NAME: percygrunwald/docker-asdf-terraform-ci-base
  GIT_AUTHOR_EMAIL: percy.grunwald@gmail.com
  GIT_AUTHOR_NAME: Percy Grunwald
jobs:
  auto_release:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v2
      - id: build-and-test
        run: script/ci.sh
