on: [push, pull_request]
env:
  DOCKER_USERNAME: percygrunwald
  IMAGE_NAME: percygrunwald/docker-asdf-terraform-ci-base
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v2
      - id: commit-hash
        run: |
          echo "::set-output name=commit-hash::$(git rev-parse --short HEAD)"
      - id: build
        run: |
          docker image ls ${IMAGE_NAME} | while read _ TAG _; do
            docker image rm -f ${IMAGE_NAME}:${TAG}
          done
          docker build --tag ${IMAGE_NAME}:git-${COMMIT_HASH} .
        env:
          COMMIT_HASH: ${{ steps.commit-hash.outputs.commit-hash }}
      - id: test
        run: |
          docker run --rm -v $PWD:/repo ${IMAGE_NAME}:git-${COMMIT_HASH} /repo/script/test.sh
        env:
          COMMIT_HASH: ${{ steps.commit-hash.outputs.commit-hash }}
      - id: docker-push
        run: |
          docker image tag ${IMAGE_NAME}:git-${COMMIT_HASH} ${IMAGE_NAME}:latest
          docker image tag ${IMAGE_NAME}:git-${COMMIT_HASH} ${IMAGE_NAME}:$(date -u +"%Y-%m-%d-%H%M%S")
          docker image ls
          echo "${DOCKER_PASSWORD}" | docker login --username ${DOCKER_USERNAME} --password-stdin
          docker image push --all-tags ${IMAGE_NAME}
        env:
          COMMIT_HASH: ${{ steps.commit-hash.outputs.commit-hash }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
